-- PoundTrades Sample Data and Admin Accounts
-- This script creates admin accounts and populates the app with realistic sample data

-- =============================================
-- ADMIN ACCOUNTS
-- =============================================

-- Note: In a real Supabase project, you would create these users through the Auth API
-- or the Supabase dashboard. This SQL is provided as a reference for what needs to be created.
-- The actual implementation would use the Auth API like:
--
-- const { data, error } = await supabase.auth.admin.createUser({
--   email: 'roger@poundtrades.co.uk',
--   password: 'Theonlywayisup69!',
--   user_metadata: { name: 'Roger Holman', role: 'admin' }
-- })

-- For reference, here are the admin accounts to be created:
-- 
-- Roger Holman
-- Email: roger@poundtrades.co.uk
-- Password: Theonlywayisup69!
-- 
-- Jonny Allum
-- Email: jonny@kliqtmedia.co.uk
-- Password: Aprilia1

-- =============================================
-- SAMPLE USERS
-- =============================================

-- Create sample users (these UUIDs would normally be generated by Supabase Auth)
-- In a real implementation, you would create these through the Auth API
INSERT INTO auth.users (id, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data)
VALUES
  -- Regular users
  ('11111111-1111-1111-1111-111111111111', 'david@example.com', 'hashed_password', NOW(), NOW(), NOW(), '{"provider":"email","providers":["email"]}', '{"name":"David Smith","role":"user"}'),
  ('22222222-2222-2222-2222-222222222222', 'sarah@example.com', 'hashed_password', NOW(), NOW(), NOW(), '{"provider":"email","providers":["email"]}', '{"name":"Sarah Johnson","role":"user"}'),
  ('33333333-3333-3333-3333-333333333333', 'mike@example.com', 'hashed_password', NOW(), NOW(), NOW(), '{"provider":"email","providers":["email"]}', '{"name":"Mike Williams","role":"user"}'),
  ('44444444-4444-4444-4444-444444444444', 'emma@example.com', 'hashed_password', NOW(), NOW(), NOW(), '{"provider":"email","providers":["email"]}', '{"name":"Emma Brown","role":"user"}'),
  ('55555555-5555-5555-5555-555555555555', 'james@example.com', 'hashed_password', NOW(), NOW(), NOW(), '{"provider":"email","providers":["email"]}', '{"name":"James Taylor","role":"user"}'),
  
  -- Tradespeople
  ('66666666-6666-6666-6666-666666666666', 'robert@example.com', 'hashed_password', NOW(), NOW(), NOW(), '{"provider":"email","providers":["email"]}', '{"name":"Robert Jones","role":"user","tradesperson":true}'),
  ('77777777-7777-7777-7777-777777777777', 'lisa@example.com', 'hashed_password', NOW(), NOW(), NOW(), '{"provider":"email","providers":["email"]}', '{"name":"Lisa Davies","role":"user","tradesperson":true}'),
  ('88888888-8888-8888-8888-888888888888', 'john@example.com', 'hashed_password', NOW(), NOW(), NOW(), '{"provider":"email","providers":["email"]}', '{"name":"John Wilson","role":"user","tradesperson":true}'),
  
  -- Business accounts
  ('99999999-9999-9999-9999-999999999999', 'contact@buildersupplies.com', 'hashed_password', NOW(), NOW(), NOW(), '{"provider":"email","providers":["email"]}', '{"name":"Builder Supplies Ltd","role":"user","business":true}'),
  ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'info@constructionmaterials.co.uk', 'hashed_password', NOW(), NOW(), NOW(), '{"provider":"email","providers":["email"]}', '{"name":"Construction Materials Co","role":"user","business":true}');

-- =============================================
-- SAMPLE LISTINGS
-- =============================================

-- Insert sample listings
INSERT INTO public.listings (title, description, price, image_url, seller_type, contact_info, user_id, created_at, boosted, location, location_name)
VALUES
  -- Bricks and blocks
  ('Reclaimed Red Bricks - 500 pieces', 'Approximately 500 reclaimed red bricks in good condition. Perfect for garden walls, features, or small extensions. Some mortar may need cleaning off. Collection only.', 150.00, 'https://images.unsplash.com/photo-1590406604579-2a8bbf1133ff', 'Public', '07700 900123', '11111111-1111-1111-1111-111111111111', NOW() - INTERVAL '2 days', FALSE, '{"lat": 51.5074, "lng": -0.1278}', 'London SE1'),
  
  ('New Concrete Blocks - 50 pieces', 'Standard concrete blocks, 440mm x 215mm x 100mm. Surplus from recent project. Never used, still on pallets. Ideal for garden walls or small construction projects.', 75.00, 'https://images.unsplash.com/photo-1590406604579-2a8bbf1133ff', 'Public', '07700 900124', '22222222-2222-2222-2222-222222222222', NOW() - INTERVAL '3 days', TRUE, '{"lat": 51.4543, "lng": -0.0098}', 'London SE10'),
  
  ('Engineering Bricks - 200 pieces', 'Class B engineering bricks, blue. High strength and low water absorption. Perfect for below DPC level construction or areas with high moisture. Approximately 200 bricks available.', 120.00, 'https://images.unsplash.com/photo-1590406604579-2a8bbf1133ff', 'Trade', '07700 900125', '66666666-6666-6666-6666-666666666666', NOW() - INTERVAL '5 days', FALSE, '{"lat": 51.5142, "lng": -0.0931}', 'London E1'),
  
  -- Timber and wood
  ('Reclaimed Timber Beams - Oak', 'Beautiful reclaimed oak beams from 19th century barn conversion. Various sizes available, most around 2.4m length. Perfect for feature beams or rustic furniture projects.', 300.00, 'https://images.unsplash.com/photo-1520454974749-611b7248ffdb', 'Trade', '07700 900126', '77777777-7777-7777-7777-777777777777', NOW() - INTERVAL '1 day', TRUE, '{"lat": 51.4613, "lng": -0.1156}', 'London SW9'),
  
  ('Plywood Sheets - 8x4ft', 'Exterior grade plywood sheets, 18mm thickness. 10 sheets available. Ideal for construction, flooring, or outdoor projects. Can deliver locally for additional fee.', 200.00, 'https://images.unsplash.com/photo-1520454974749-611b7248ffdb', 'Business', '07700 900127', '99999999-9999-9999-9999-999999999999', NOW() - INTERVAL '7 days', FALSE, '{"lat": 51.5311, "lng": -0.0481}', 'London E8'),
  
  ('Treated Fence Panels - 6x6ft', 'Pressure treated feather edge fence panels. 8 panels available. Excellent condition, only 1 year old. Removed due to garden redesign.', 160.00, 'https://images.unsplash.com/photo-1520454974749-611b7248ffdb', 'Public', '07700 900128', '33333333-3333-3333-3333-333333333333', NOW() - INTERVAL '4 days', FALSE, '{"lat": 51.4170, "lng": -0.0668}', 'London SE25'),
  
  -- Doors and windows
  ('UPVC Double Glazed Window', 'White UPVC double glazed window, 1200mm x 900mm. Removed during renovation, in excellent condition. Energy efficient double glazing with key locking handle.', 95.00, 'https://images.unsplash.com/photo-1516484681072-c3a5ec8c6320', 'Public', '07700 900129', '44444444-4444-4444-4444-444444444444', NOW() - INTERVAL '6 days', FALSE, '{"lat": 51.4635, "lng": -0.0921}', 'London SE24'),
  
  ('Solid Oak Internal Doors - x3', 'Three solid oak internal doors, 1981mm x 762mm x 35mm. Contemporary style with vertical panels. Excellent condition, hardware not included. Collection only.', 225.00, 'https://images.unsplash.com/photo-1516484681072-c3a5ec8c6320', 'Trade', '07700 900130', '88888888-8888-8888-8888-888888888888', NOW() - INTERVAL '8 days', TRUE, '{"lat": 51.5505, "lng": -0.1881}', 'London NW3'),
  
  ('Composite Front Door - Anthracite Grey', 'Modern composite front door in anthracite grey. 2100mm x 900mm. Multipoint locking system, letterbox and chrome hardware included. Excellent thermal and security ratings.', 350.00, 'https://images.unsplash.com/photo-1516484681072-c3a5ec8c6320', 'Business', '07700 900131', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', NOW() - INTERVAL '10 days', FALSE, '{"lat": 51.4305, "lng": -0.0628}', 'London SE20'),
  
  -- Tools and equipment
  ('DeWalt Power Tools Set', 'DeWalt 18V cordless power tools set. Includes drill, impact driver, circular saw and reciprocating saw. All in good working order with 2 batteries, charger and carry case.', 280.00, 'https://images.unsplash.com/photo-1581147036324-c47a03a81d48', 'Public', '07700 900132', '55555555-5555-5555-5555-555555555555', NOW() - INTERVAL '12 days', FALSE, '{"lat": 51.4305, "lng": -0.0628}', 'London SE20'),
  
  ('Scaffold Tower - 6m Working Height', 'Aluminium scaffold tower with 6m working height. Includes all frames, braces, platforms and stabilizers. Conforms to EN1004 standards. Collection only with suitable transport.', 420.00, 'https://images.unsplash.com/photo-1581147036324-c47a03a81d48', 'Trade', '07700 900133', '66666666-6666-6666-6666-666666666666', NOW() - INTERVAL '9 days', TRUE, '{"lat": 51.5142, "lng": -0.0931}', 'London E1'),
  
  ('Cement Mixer - Belle Minimix 150', 'Belle Minimix 150 cement mixer. 240V electric. Good working condition, recently serviced. Drum capacity 136 litres, output 85 litres. Collection only.', 175.00, 'https://images.unsplash.com/photo-1581147036324-c47a03a81d48', 'Business', '07700 900134', '99999999-9999-9999-9999-999999999999', NOW() - INTERVAL '15 days', FALSE, '{"lat": 51.5311, "lng": -0.0481}', 'London E8'),
  
  -- Miscellaneous building materials
  ('Insulation Boards - Celotex 50mm', '10 sheets of Celotex GA4050 insulation board. 2400mm x 1200mm x 50mm. High performance PIR insulation with thermal conductivity of 0.022 W/mK. Collection only.', 200.00, 'https://images.unsplash.com/photo-1581147036324-c47a03a81d48', 'Business', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', NOW() - INTERVAL '11 days', FALSE, '{"lat": 51.4305, "lng": -0.0628}', 'London SE20'),
  
  ('Roof Tiles - Redland 49', 'Approximately 500 Redland 49 concrete roof tiles in Breckland Brown. Removed during re-roofing, in good condition. Ideal for extensions or repairs. Collection only.', 300.00, 'https://images.unsplash.com/photo-1581147036324-c47a03a81d48', 'Trade', '07700 900135', '77777777-7777-7777-7777-777777777777', NOW() - INTERVAL '14 days', TRUE, '{"lat": 51.4613, "lng": -0.1156}', 'London SW9'),
  
  ('Paving Slabs - Indian Sandstone', 'Premium Indian sandstone paving slabs in Autumn Brown. Approximately 15m² coverage. Various sizes in the pack. Surplus from recent landscaping project.', 250.00, 'https://images.unsplash.com/photo-1581147036324-c47a03a81d48', 'Public', '07700 900136', '11111111-1111-1111-1111-111111111111', NOW() - INTERVAL '16 days', FALSE, '{"lat": 51.5074, "lng": -0.1278}', 'London SE1');

-- =============================================
-- SAMPLE FAVORITES
-- =============================================

-- Insert sample favorites
INSERT INTO public.favorites (user_id, listing_id, created_at)
VALUES
  ('11111111-1111-1111-1111-111111111111', 4, NOW() - INTERVAL '1 day'),
  ('11111111-1111-1111-1111-111111111111', 7, NOW() - INTERVAL '2 days'),
  ('22222222-2222-2222-2222-222222222222', 1, NOW() - INTERVAL '3 days'),
  ('22222222-2222-2222-2222-222222222222', 10, NOW() - INTERVAL '1 day'),
  ('33333333-3333-3333-3333-333333333333', 2, NOW() - INTERVAL '5 days'),
  ('33333333-3333-3333-3333-333333333333', 8, NOW() - INTERVAL '2 days'),
  ('44444444-4444-4444-4444-444444444444', 3, NOW() - INTERVAL '4 days'),
  ('44444444-4444-4444-4444-444444444444', 5, NOW() - INTERVAL '1 day'),
  ('55555555-5555-5555-5555-555555555555', 6, NOW() - INTERVAL '3 days'),
  ('55555555-5555-5555-5555-555555555555', 9, NOW() - INTERVAL '2 days');

-- =============================================
-- SAMPLE UNLOCKS
-- =============================================

-- Insert sample unlocks
INSERT INTO public.unlocks (user_id, listing_id, amount, created_at)
VALUES
  ('11111111-1111-1111-1111-111111111111', 5, 100, NOW() - INTERVAL '1 day'),
  ('22222222-2222-2222-2222-222222222222', 3, 100, NOW() - INTERVAL '2 days'),
  ('33333333-3333-3333-3333-333333333333', 8, 100, NOW() - INTERVAL '3 days'),
  ('44444444-4444-4444-4444-444444444444', 1, 100, NOW() - INTERVAL '1 day'),
  ('55555555-5555-5555-5555-555555555555', 10, 100, NOW() - INTERVAL '2 days'),
  ('66666666-6666-6666-6666-666666666666', 2, 100, NOW() - INTERVAL '3 days'),
  ('77777777-7777-7777-7777-777777777777', 6, 100, NOW() - INTERVAL '1 day'),
  ('88888888-8888-8888-8888-888888888888', 4, 100, NOW() - INTERVAL '2 days'),
  ('99999999-9999-9999-9999-999999999999', 7, 100, NOW() - INTERVAL '3 days'),
  ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 9, 100, NOW() - INTERVAL '1 day');